name: Release
on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write
  pages: write
  pull-requests: write
  statuses: write

jobs:
  release:
    name: Run Release Manager

    runs-on: ubuntu-latest

    steps:
#      - name: Load Secrets
#        uses: 1password/load-secrets-action@v1
#        with:
#          export-env: true
#        env:
#          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
#          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
#          GITHUB_APP_ID: op://op-github-devops/cosmic-agent-labs/app-id
#          GITHUB_PRIVATE_KEY: op://op-github-devops/cosmic-agent-labs/private-key

#      - name: Create GitHub App Token
#        id: app-token
#        uses: actions/create-github-app-token@v1
#        with:
#          app-id: ${{ env.GITHUB_APP_ID }}
#          private-key: ${{ env.GITHUB_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
#          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Pull all previous tags
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Conventional Changelog Action
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-git-pull: true
          skip-version-file: false
          version-file: charts/sxt-node-chart/Chart.yaml
          git-push: true
          skip-on-empty: false # Always create commit
          tag-prefix: ""  #remove the 'v' prefix in tag

#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.conventional-changelog.outputs.tag }}
#          body: ${{ steps.conventional-changelog.outputs.changelog }}
#          token: ${{ steps.app-token.outputs.token }}
#          makeLatest: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
