name: Release
on:
  push:
    branches:
      - main

permissions: write-all

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  release:
    name: Run Release Manager

    runs-on: ubuntu-latest

    steps:
#      - name: Load Secrets
#        uses: 1password/load-secrets-action@v1
#        with:
#          export-env: true
#        env:
#          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
#          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
#          GITHUB_APP_ID: op://op-github-devops/cosmic-agent-labs/app-id
#          GITHUB_PRIVATE_KEY: op://op-github-devops/cosmic-agent-labs/private-key

#      - name: Create GitHub App Token
#        id: app-token
#        uses: actions/create-github-app-token@v1
#        with:
#          app-id: ${{ env.GITHUB_APP_ID }}
#          private-key: ${{ env.GITHUB_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
#          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Pull all previous tags
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Conventional Changelog Action
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
#          github-token: ${{ steps.app-token.outputs.token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-git-pull: true
          skip-version-file: false
          version-file: charts/sxt-node-chart/Chart.yaml
          git-push: true
          skip-on-empty: false # Always create commit
          tag-prefix: ""  #remove the 'v' prefix in tag

#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.conventional-changelog.outputs.tag }}
#          body: ${{ steps.conventional-changelog.outputs.changelog }}
#          token: ${{ steps.app-token.outputs.token }}
#          makeLatest: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        continue-on-error: true
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Continue chart-release
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          mkdir -p .cr-index .cr-release-packages
          # download index.yaml or start as empty .. the index.yaml needs to be placed inside .cr-index/
          curl https://spaceandtimelabs.github.io/sxt-node-chart-repo/index.yaml -o .cr-index/index.yaml || touch .cr-index/index.yaml
          # download all known release packages, the packages needs to be placed inside .cr-release-packages/
          for i in `git tag|grep sxt-node-chart`; do
          curl -L https://github.com/spaceandtimelabs/sxt-node-chart-repo/releases/download/${i}/${i}.tgz -o .cr-release-packages/${i}.tgz
          file .cr-release-packages/${i}.tgz |grep "gzip compressed data" || rm -f .cr-release-packages/${i}.tgz
          done
          # cr command.. will fail
          cr index --owner "spaceandtimelabs" --git-repo sxt-node-chart-repo --push || cat .cr-index/index.yaml
          git push origin HEAD:gh-pages
